### PR TITLE
[BE] feat: Add tables for interest topics feature

### PR DESCRIPTION
**Pull request by AngelC32**
The purpose of this PR is to add the required tables for the interest topics feature in database migrations.

The following tables have been added: 
- SOC_APP_M_USERS_INTERESTS
- SOC_APP_USERS_INTEREST_TOPICS.

# Tables description

<table>
  <thead>
    <tr>
      <th>Tabla</th>
      <th>Descripción</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>SOC_APP_M_USERS_INTERESTS</td>
      <td>This table will be a master that will contain all the interests that will be held within the social network.</td>
    </tr>
    <tr>
      <td>SOC_APP_USERS_INTEREST_TOPICS</td>
      <td>This table relates users to the interest topics they selected.</td>
    </tr>
  </tbody>
</table>

### CODE REVIEW

**Review by eds000n — DISMISSED** [review]

**Review by aronlabr — CHANGES_REQUESTED** [review]
SOC_APP_M_USERS_INTERESTS and others needs to have "sa" as prefix schema (i.e sa.SOC_APP_M_USERS_INTERESTS) in the *.up.sql files

**Comment by AngelC32** [comment]
> SOC_APP_M_USERS_INTERESTS and others needs to have "sa" as prefix schema (i.e sa.SOC_APP_M_USERS_INTERESTS) in the *.up.sql files
Thanks, please check it again

**Review by aronlabr — DISMISSED** [review]
Looks good. 👍

**Review by aronlabr — APPROVED** [review]
Based on our previous discussion in the [PR](https://github.com/unmsmfisi-socialapplication/social_app/pull/534#pullrequestreview-1711470057), it will be necessary in the future to ensure that the tables are not tied to a specific schema name. Currently, this should not cause any issues.

**Comment by AngelC32** [comment]
> Based on our previous discussion in the [PR](https://github.com/unmsmfisi-socialapplication/social_app/pull/534#pullrequestreview-1711470057), it will be necessary in the future to ensure that the tables are not tied to a specific schema name. Currently, this should not cause any issues.

Thanks for your feedback.
 @francosilva25, is it necessary to specify the schema in database migrations scripts?

**Comment by francosilva25** [comment]
Hi Angel

The database schema is being entered by the environment variables, as coordinated with Aaron Blas the migrations should work regardless of the schema name.

In this case it is not necessary to enter the schema name.

Regards

Franco Silva.

**Pull request merged**
