### PR TITLE
[DATA] Spam detection feature integration for develop

### PR DESCRIPTION
**Pull request by gustavo-guerreros1**
In this activity, I propose to develop spam detection models using two machine learning approaches: Naive Bayes and Logistic Regression. The main objective is to create an effective system that can identify and filter unwanted comments (spam) from those that are legitimate (ham).

### CODE REVIEW

**Comment by ZDev-19** [comment]
According to actual date 8/09 , the feature of Spam Detection , requested by the Issue https://github.com/orgs/unmsmfisi-socialapplication/projects/1/views/2?filterQuery=DATA&pane=issue&itemId=37493028 now adds Data Preprocessing (based on potential data of the final project) and four classifiers models (Random Forest , Knn , Naive Bayes and Logistic Regression) . According to the meeting in 3/09 one last model is pending in order to comparison and final model election for Spam Detection.

**Review by eds000n — COMMENTED** [review]
PR must be done against `develop` branch. Also your PR shouldn't include changes which aren't yours, in this case you have some backend stuff while the PR is data related...
Also, why do we need jupiter files here? those are mainly for prototyping and not for production, there's no folder structure indicating such use

**Comment by eds000n** [comment]
also, why are you adding data to the repo? I'm refering to the csv file

**Comment by ZDev-19** [comment]
Pull request closed due to new project structure according to meeting at 8/9

**Pull request closed without merging**
