### PR TITLE
[QA] Update for contract of post creation

### PR DESCRIPTION
**Pull request by legolas1902**
Update of the post creation contract following the activity pub protocol, documentation at the following link https://github.com/unmsmfisi-socialapplication/social_app/issues/687

### CODE REVIEW

**Comment by luzelenatt** [comment]
The contract must specify the different scenarios and the response of each of them, changes are required to this PR

**Comment by legolas1902** [comment]
@luzelenatt in the issue https://github.com/unmsmfisi-socialapplication/social_app/issues/687 you will find the scenarios and the response for each case

**Comment by legolas1902** [comment]
@luzelenatt the issue https://github.com/unmsmfisi-socialapplication/social_app/issues/687 contains the use cases made of 
the contract, as well as their responses.

**Review by felixalfonsofernandez — APPROVED** [review]
the contract for the creation of the post complies with the established protocol

**Pull request merged**
