### PR TITLE
[QA] Test for Profile feature using POST method in Postman

### PR DESCRIPTION
**Pull request by legolas1902**
The tests are generated according to the documentacion of the next issue https://github.com/unmsmfisi-socialapplication/social_app/issues/745, the tests were performed in postman

### CODE REVIEW

**Comment by luzelenatt** [comment]
As the teacher mentioned, this PR must be run with the CI. In addition, the PR is very long, corrections are requested

**Comment by legolas1902** [comment]
@luzelenatt the dev ops team requires the collection information to perform the integration with the github, this includes the tests, the endpoint and the examples, it is in proportion to the tests performed.

**Comment by luzelenatt** [comment]
Ok @legolas1902 For the next PR's it is recommended that smaller PR's be created, however the test was used using postman and works correctly

**Review by felixalfonsofernandez — APPROVED** [review]
Profile function testing with post method meets requirements for dev ops

**Pull request merged**
