### PR TITLE
[DEVOPS] Implementing dependabot

### PR DESCRIPTION
**Pull request by aronlabr**
Dependabot is a tool that automates dependency updates to ensure our project remains secure and up-to-date. This PR aims for implementing Dependabot in our project. Resolving the following issue #581

### CODE REVIEW

**Comment by aronlabr** [comment]
It will be necessary to obtain feedback from the respective teams, @AnthonyRicse98 , @LuiggiPasacheL, and @andresrdlc, about how to group dependencies, the frequency for checking, and the quantity of the PRs.

**Comment by aronlabr** [comment]
Adding new label
image

**Comment by aronlabr** [comment]
Trying implementation in a [personal fork](https://github.com/aronlabr/social_app) of the repository
image

**Comment by aronlabr** [comment]
Regarding grouping, for example, in the context of frontend dependencies:

If any dependency related to Material-UI (mui) or Emotion requires an update, Dependabot will generate a pull request (PR) that consolidates these changes as a user interface (UI) update.

The @mui* notation is a pattern-matching mechanism that can be used to specify dependencies associated with Material-UI. Similarly, other dependencies can be explicitly defined, such as typescript.
```yaml
groups:
      ui:
        patterns:
          - "@mui*"
          - "@emotion*"
      ts:
        patterns:
          - "@types*"
          - "typescript"
        ignore-patterns:
          - "@types/jest"
      testing:
        patterns:
          - "*jest*"
          - "testing*"
```

**Comment by aronlabr** [comment]
Enabling Dependabot in the repository
image

**Review by LuiggiPasacheL — COMMENTED** [review]
Proposal groups for backend dependencies
**group: HTTP**
- chi
- websocket
- cors

**group: database** 
- pq
- migrate

**group: Indirects**
- errwarp
- go-multierror
- atomic

**group: utils**
- crypto

**Comment by aronlabr** [comment]
> Proposal groups for backend dependencies

The changes were added and manually test in a fork repo
image

**Comment by aronlabr** [comment]
For a brief explanation of the file

1. package-ecosystem: "gomod"
Specifies the package ecosystem, in this case, Go modules.
4. target-branch: "develop"
 Specifies the branch where Dependabot should create pull requests. In this case, it's the "develop" branch.
7. directory: "/backend"
 Indicates the directory or path within the repository where Dependabot should look for dependencies. For Go modules, it's in the "/backend" directory.
10. schedule: interval: "weekly"
 Sets the frequency of dependency updates. It's set to weekly, meaning Dependabot will check for updates every week.
13. open-pull-requests-limit: 2
Limits the number of open pull requests created by Dependabot to 2 at a time.
16. allow: - dependency-type: "all"
Specifies that Dependabot should consider all types of dependency updates.
19. ignore: - dependency-name: "*" update-types: ["version-update:semver-major"]
Instructs Dependabot to ignore updates with major version changes for all dependencies.
22. pull-request-branch-name: separator: "-"
Sets the separator for branch names created by Dependabot.
25. commit-message: prefix: "[BE] "
Specifies a prefix for commit messages generated by Dependabot. In this case, it's "[BE]" for backend updates.
28. labels: - "backend" - "dependencies"
Adds labels to the generated pull requests, such as "backend" and "dependencies."
31. groups:
Organizes dependencies into groups with specific patterns.

      - http: patterns: ["go-chi", "websocket"]
    Groups dependencies related to HTTP handling using patterns.
      - database: patterns: ["pq", "migrate"]
     Groups database-related dependencies using patterns.
      - indirects: patterns: ["hashicorp", "atomic"]
    Groups indirect dependencies with specific patterns.
      - utils: patterns: ["crypto"]
    Groups utility dependencies with a pattern.
 

The other updates follow a similar structure for different package ecosystems (npm, github-actions, docker) with ecosystem-specific configurations.

**Review by pieroHernandezC — APPROVED** [review]

**Review by LuiggiPasacheL — APPROVED** [review]

**Pull request merged**
