### PR TITLE
[BE] Implementation of complementary tests for comments functionality

### PR DESCRIPTION
**Pull request by Manuelda10**
Some routes have been fixed and refactored to accommodate testing by the QA team in POSTMAN. The current routes are the following:

1. GET {BASE_URL}/comments to get general comments.
2. GET {BASE_URL}/comments/{COMMENT_ID} to get a specific comment.
3. POST {BASE_URL}/comments to create a new comment.
4. PUT {BASE_URL}/comments/{COMMENT_ID} to update a specific comment.
5. DELETE {BASE_URL}/comments/{COMMENT_ID} to force deletion of a specific comment.

| Type | ROUTE             | BODY | SUCCESSFUL RESPONSE |
|  :------:  | :---------------- | :------ | ----: |
| GET | {BASE_URL}/comments |   -   | { "response": [ { }, { } ], "status" : "ok" } |
| GET | {BASE_URL}/comments/{COMMENT_ID} |   -   | { "response": {}, "status" : "ok" } |
| POST | {BASE_URL}/comments | { "userID": 1, "postID": 5, "comment": "Example",  "insertionDate": "2023-11-03T08:00:00Z", "updateDate": "2023-11-03T08:00:00Z", "parentCommentID": null } | {"response": "Comment created successfully", "status": "OK"} |
| PUT | {BASE_URL}/comments/{COMMENT_ID} |  { "userID": 1, "postID": 5, "comment": "Example updated",  "insertionDate": "2023-11-03T08:00:00Z", "updateDate": "2023-11-04T08:00:00Z", "parentCommentID": 2 }  | {"response": "Comment updated successfully", "status": "OK"} |
| DELETE | {BASE_URL}/comments/{COMMENT_ID} | - | {"response": "Comment deleted successfully", "status": "OK"} |

The unit test suite has also been updated to be able to test comments in development. These tests can be run by entering **internal/comment/infrastructure** and writing the following in the console: `go test`

### CODE REVIEW

**Comment by AngelGio** [comment]
The unit tests could be improved or refactored to make them easier to read. I see that in the code there are repetitive blocks that could be reduced. Please check

**Comment by Manuelda10** [comment]
The unit test code has been refactored to make it easier to understand and improve its readability. You can test it by running `go test` in `backend/internal/comment/infrastructure`
image

**Comment by AngelGio** [comment]
Everything correct, corrections were considered

**Review by AngelGio — APPROVED** [review]
reviewed

**Pull request merged**
